### ISSUE TITLE
Updating a key resets it's expiry

### ISSUE THREAD

**Issue by ryanslade** [dustin/gomemcached#18]
https://github.com/dustin/gomemcached/blob/master/client/mc.go#L389

Why is this done? It appears to ignore the expiry value passed in and reset it to 0.

In our system, this leads to updated keys never expiring. The fix is easy, but wondering why this was done in the first place?

**Comment by dustin** [comment]
It's a bit unclear.  It seemed that every path was wrong, but that one probably looks more wrong than resetting it to the supplied value.
